### ISSUE TITLE
[Bug] Very high message roundtrip ping when the lib is loaded.

### ISSUE THREAD

**Issue by FightMan01** [kiki7000/discord.py-components#72]
## Bug Line
> I don't know where is the actual bug. My bot is over 8000 servers.
<img width="185" alt="image" src="https://user-images.githubusercontent.com/29693718/120291150-495a5480-c2c3-11eb-888d-4cd6122b3c61.png">
After a bot restart with the Cog unloaded the bot works fine. When I load the Cog it slows down.

## Excpected Action
> Just work

## Actual Action
> Well it works but slows down the bot.

## Reproducing the action
> Module loaded in a Cog:
```py
    def __init__(self, client):
        self.client = client
        self.connection = client.dbconnection
        if not hasattr(client, "component_client"):
            self.component_client = DiscordComponents(client)
        else:
            self.component_client = client.component_client
```
Also it is present in my on_ready() function as well. The cog loads when the bot is ready.

## Possible Solution
> I didn't manage to find anything.

## Environment
- Python v3.8.5-final
- discord.py v1.7.2-final
- aiohttp v3.6.2
- system info: Linux 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021
Latest version of the lib from GitHub. 

## Check
- [x] Are you using the newest version?
- [ ] Is this bug related to security issues?

**Comment by FightMan01** [comment]
Network: https://www.speedtest.net/result/c/53809c07-3978-4096-be0f-d5219dffb35a

**Comment by kiki7000** [comment]
Fixed on 1ba7404bd1b167a2145cfe332720ab6a34daa8da but not released

**Comment by FightMan01** [comment]
Well it did not fix for me. I installed this lib yesterday using `pip install git+https://github.com/kiki7000/discord.py-components.git`

**Comment by FightMan01** [comment]
But I made some modifications for example to always add a listener even I turn change_discord_methods to False. Somehow if I turn that to True my bot slows down but when I turn it to False the performance will be normal. 
Also I reworked the on_socket_response a bit when I tried. to investigate the issue but I don't think that's important. 
https://github.com/FightMan01/discord.py-components/commit/b3a44dd4a772cb87b7d167f58e0ee212eea0a89d

**Comment by kiki7000** [comment]
Was the ping lower when the previous version?

**Comment by FightMan01** [comment]
No, the ping was very high even in the version 0.5.2.4

**Comment by kiki7000** [comment]
I mean on version 0.5.1 and lower

**Comment by FightMan01** [comment]
I didn't try that. I just tried the PyPi version and the GitHub version.

**Comment by kiki7000** [comment]
Did you try with `add_listener` disabled?

**Comment by FightMan01** [comment]
Well, the on_button_click event is very important for me, so I didn't do that.

**Comment by kiki7000** [comment]
Oh, that is not related to `add_listener`.
That is for users who are using discord-py-slash-command

**Comment by FightMan01** [comment]
Oh :D 
But I'm using discord-py-slash-command as well 😅

**Comment by kiki7000** [comment]
Oh
Could you try it?

**Comment by FightMan01** [comment]
Well yes, but I noticed one more thing with `interaction.respond()`.
When I used it, the roundtrip was about `1200ms`. So I decided to write the request myself:
```py
                #await res.respond(type=InteractionType.UpdateMessage, embed=embed, content=None)
                token = res.interaction_token
                compid = res.interaction_id
                data = {}
                data["content"] = None
                embeds = [embed]
                if embeds:
                    embeds = list(map(lambda x: x.to_dict(), embeds))
                    data["embeds"] = embeds
                async with aiohttp.ClientSession() as session:
                    await session.post(f"https://discord.com/api/v8/interactions/{compid}/{token}/callback", json={"type": InteractionType.UpdateMessage, "data": data})
```
And I noticed with this I get about `310ms` which is acceptable in Hungary. 
To be honest I don't really understand what cause this problem.

**Comment by kiki7000** [comment]
Could you replace ```py
                async with aiohttp.ClientSession() as session:
                    await session.post(f"https://discord.com/api/v8/interactions/{compid}/{token}/callback", json={"type": InteractionType.UpdateMessage, "data": data})
``` in you code with
```py
bot.http.request(discord.http.Route("POST", f"/interactions/{compid}/{token}/callback"), json={"type": InteractionType.UpdateMessage, "data": data})

**Comment by FightMan01** [comment]
Hmm, about 300ms

**Comment by FightMan01** [comment]
I use this formula:
```py
                t1 = time.perf_counter()
                await self.client.http.request(discord.http.Route("POST", f"/interactions/{compid}/{token}/callback"), json={"type": InteractionType.UpdateMessage, "data": data})
                t2 = time.perf_counter()
                print(f"Latency: {round((t2-t1)*1000)}ms")
```

**Comment by FightMan01** [comment]
But it's still thinking a lot and sometimes fail

https://user-images.githubusercontent.com/29693718/120505330-29ab5500-c3c5-11eb-8bd4-48aae7847fde.mov

**Comment by FightMan01** [comment]
Ok, I managed to figure out something. 
I made another bot client and added it only 1 server. And it works very fast and fine. Same code, same environment, same everything but a different bot client. 
My main bot is over 8000 servers. Maybe that is the "problem"?

**Comment by kiki7000** [comment]
But your bot's ping was fine until you used this library

**Comment by FightMan01** [comment]
Yes, so that's why this is very confusing for me
